const countriesData = {
  Africa: {
    1: 'Algeria',
    2: 'Angola',
    3: 'Benin',
    4: 'Botswana',
    5: 'Burkina Faso',
    6: 'Burundi',
    7: 'Cameroon',
    8: 'Central African Republic',
    9: 'Chad',
    10: 'Comoros',
    11: 'Congo',
    12: 'Congo, Democratic Republic of the',
    13: 'Côte d’Ivoire',
    14: 'djibouti',
    15: 'Egypt',
    16: 'Equatorial Guinea',
    17: 'Eritrea',
    18: 'Eswatini',
    19: 'Ethiopia',
    20: 'Gabon',
    21: 'Gambia',
    22: 'Ghana',
    23: 'Guinea',
    24: 'Guinea-Bissau',
    25: 'Kenya',
    26: 'Lesotho',
    27: 'Liberia',
    28: 'Libya',
    29: 'Madagascar',
    30: 'Malawi',
    31: 'Mali',
    32: 'Mauritania',
    33: 'Morocco',
    34: 'Mozambique',
    35: 'Namibia',
    36: 'Niger',
    37: 'Nigeria',
    38: 'Rwanda',
    39: 'Sao Tome and Principe',
    40: 'Seychelles',
    41: 'Sierra Leone',
    42: 'Somalia',
    43: 'South Africa',
    44: 'South Sudan',
    45: 'Sudan',
    46: 'Swaziland',
    47: 'Tanzania',
    48: 'Togo',
    49: 'Tunisia',
    50: 'Uganda',
    51: 'Zambia',
    52: 'Zimbabwe',
  },
  Oceania: {
    1: 'Australia',
    2: 'Fiji',
    3: 'New Zealand',
    4: 'Pacific Islands',
    5: 'Samoa',
  },

  Antarctica: {
    1: 'Antarctica',
  },

  Europe: {
    1: 'Albania',
    2: 'Andorra',
    3: 'Armenia',
    4: 'Austria',
    5: 'Azerbaijan',
    6: 'Belarus',
    7: 'Belgium',
    8: 'Bosnia and Herzegovina',
    9: 'Bulgaria',
    10: 'Croatia',
    11: 'Cyprus',
    12: 'Czech Republic',
    13: 'Denmark',
    14: 'Estonia',
    15: 'Finland',
    16: 'France',
    17: 'Georgia',
    18: 'Germany',
    19: 'Greece',
    20: 'Hungary',
    21: 'Iceland',
    22: 'Ireland',
    23: 'Italy',
    24: 'Latvia',
    25: 'Lithuania',
    26: 'Luxembourg',
    27: 'Malta',
    28: 'Moldova',
    29: 'Monaco',
    30: 'Netherlands',
    31: 'Norway',
    32: 'Poland',
    33: 'Portugal',
    34: 'Romania',
    35: 'Russia',
    36: 'Slovakia',
    37: 'Slovenia',
    38: 'Spain',
    39: 'Sweden',
    40: 'Switzerland',
    41: 'Turkey',
    42: 'Ukraine',
    43: 'United Kingdom',
  },

  Asia: {
    1: 'Afghanistan',
    2: 'Bangladesh',
    3: 'Bhutan',
    4: 'China',
    5: 'India',
    6: 'Indonesia',
    7: 'Iran',
    8: 'Iraq',
    9: 'Israel',
    10: 'Japan',
    11: 'Kuwait',
    12: 'Malaysia',
    13: 'Maldives',
    14: 'Mongolia',
    15: 'Nepal',
    16: 'Pakistan',
    17: 'Qatar',
    18: 'Saudi Arabia',
    19: 'Singapore',
    20: 'South Korea',
    21: 'Taiwan',
    22: 'Thailand',
    23: 'Turkey',
    24: 'United Arab Emirates',
  },

  America: {
    1: 'Argentina',
    2: 'Brazil',
    3: 'Canada',
    4: 'Chile',
    5: 'Colombia',
    6: 'Costa Rica',
    7: 'Cuba',
    8: 'Dominican Republic',
    9: 'Ecuador',
    10: 'El Salvador',
    11: 'Guatemala',
    12: 'Honduras',
    13: 'Mexico',
    14: 'Nicaragua',
    15: 'Panama',
    16: 'Paraguay',
    17: 'Peru',
    18: 'Puerto Rico',
    19: 'Uruguay',
    20: 'Venezuela',
  },
}

export default countriesData

// MM: DM: instead of having an object of nested objects like this above, can i use a specific API that contains the list of all countries ?
